version: 2

sources:
  - name: sportmetrics_raw
    database: sportmetrics-480616
    schema: Foufous_de_Sochaux
    tables:
      - name: team_boxscores
      - name: team_games_dataset
      - name: team_players_personal_info
      - name: team_players_stats
      - name: team_training_sessions
