version: 2

sources:
  - name: foufous_de_sochaux
    schema: Foufous_de_Sochaux
    description: "Raw tables imported from Airbyte for Foufous de Sochaux"
    
    tables:
      - name: players_personal_info
        description: "Player demographic & physical data"

      - name: players_stats
        description: "Player per-game performance stats"

      - name: team_boxscores
        description: "Team-level boxscores per match (kept for FK integrity)"

      - name: team_games
        description: "Team-level game metadata and outcomes"

      - name: team_training_sessions
        description: "Training KPI per session per player"
