name: 'sportmetrics_dbt'
version: '1.0.0'
config-version: 2

profile: 'user'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  sportmetrics_dbt:
    +materialized: view

    staging:
      +schema: staging

    marts:
      +schema: marts
